version: '3'
services:
  db:
    image: mysql:latest
    container_name: mysql
    expose:
     - "3306"
    environment:
     MYSQL_DATABASE: bit
     MYSQL_USER: bit
     MYSQL_PASSWORD: bit
     MYSQL_ROOT_PASSWORD: bit
     TZ: Asia/Seoul
    command: 
     - --character-set-server=utf8mb4
     - --collation-server=utf8mb4_unicode_ci
    volumes:
     - mysql-database:/var/lib/mysql-docker
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
     - "80:80/tcp"
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf #마운트할 디렉토리: docker image 내부 디렉토리
     - ./staticfiles:/project/staticfiles
     - ./media:/project/media
    depends_on:
     - web
  web:
    build:
      context: .
      dockerfile: dockerfile
    container_name: wining
    command: /bin/sh -c "/migrate.sh" && gunicorn Wining.wsgi:application --bind 0.0.0.0:8000
    volumes:
     - ./staticfiles:/project/staticfiles
     - ./media:/project/media
    expose:
     - "8000"
    depends_on:
     - db
volumes: 
  mysql-database:  

  
     
 

