version: '3'
services:
  db:
    image: mysql:8.0.34
    container_name: mysql
    expose:
     - "3307"
    environment:
     MYSQL_DATABASE: bit
     MYSQL_USER: bit
     MYSQL_PASSWORD: bit
     MYSQL_ROOT_PASSWORD: bit
     MYSQL_TCP_PORT: 3307
     TZ: Asia/Seoul
    command: 
     - --character-set-server=utf8mb4
     - --collation-server=utf8mb4_unicode_ci
    healthcheck: 
      test: ["CMD-SHELL", "mysql -uroot -pbit bit < /save.sql"]
      interval: 1s
      timeout: 1m
      start_period: 0s
      retries: 0
    volumes:
     - ./save.sql:/save.sql
     - mysql-database:/var/lib/mysql-docker	#mysql-database:/var/lib/mysql The designated data directory /var/lib/mysql/ is unusable. You can remove all files that the server added to it. 
  web:
    build:
      context: .
      dockerfile: dockerfile
    container_name: wining
    command: sh /migrate.sh
    volumes:
     - ./staticfiles:/project/staticfiles
     - ./media:/project/media
    expose:
     - "8001"
    depends_on:
     - db
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
     - "80:80/tcp"
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf #마운트할 디렉토리: docker image 내부 디렉토리
     - ./staticfiles:/project/staticfiles
     - ./media:/project/media
    depends_on:
     - web
volumes: 
  mysql-database:  

  
     
 

